// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////


// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
lv_obj_t * ui_Screen1;
lv_obj_t * ui_Screen1_Button4;
lv_obj_t * ui_Screen1_Label6;
void ui_event_Screen1_Button5(lv_event_t * e);
lv_obj_t * ui_Screen1_Button5;
lv_obj_t * ui_Screen1_Label7;
void ui_event_Screen1_Button2(lv_event_t * e);
lv_obj_t * ui_Screen1_Button2;
lv_obj_t * ui_Screen1_Label2;
lv_obj_t * ui_Screen1_Panel2;
lv_obj_t * ui_Screen1_Label8;
lv_obj_t * ui_Screen1_Label9;
lv_obj_t * ui_Screen1_Panel3;
lv_obj_t * ui_Screen1_Label4;
lv_obj_t * ui_Screen1_Label1;
void ui_event_Screen1_Button7(lv_event_t * e);
lv_obj_t * ui_Screen1_Button7;
lv_obj_t * ui_Screen1_Label10;


// SCREEN: ui_Screen2
void ui_Screen2_screen_init(void);
lv_obj_t * ui_Screen2;
lv_obj_t * ui_Screen2_Dropdown2;
lv_obj_t * ui_Screen2_Button8;
lv_obj_t * ui_Screen2_Label11;
lv_obj_t * ui_Screen2_Button9;
lv_obj_t * ui_Screen2_Label12;
lv_obj_t * ui_Screen2_Button10;
lv_obj_t * ui_Screen2_Label13;
lv_obj_t * ui_Screen2_Panel3;
lv_obj_t * ui_Screen2_Keyboard1;
void ui_event_Screen2_Button11(lv_event_t * e);
lv_obj_t * ui_Screen2_Button11;
lv_obj_t * ui_Screen2_Label14;
void ui_event_Screen2_TextArea2(lv_event_t * e);
lv_obj_t * ui_Screen2_TextArea2;
void ui_event_Screen2_Button12(lv_event_t * e);
lv_obj_t * ui_Screen2_Button12;
void ui_event_Screen2_Label15(lv_event_t * e);
lv_obj_t * ui_Screen2_Label15;
lv_obj_t * ui_Screen2_Panel5;
lv_obj_t * ui_Screen2_Label19;
lv_obj_t * ui_Screen2_Label20;
lv_obj_t * ui_Screen2_Label21;


// SCREEN: ui_Screen3
void ui_Screen3_screen_init(void);
lv_obj_t * ui_Screen3;
lv_obj_t * ui_Screen3_Button13;
lv_obj_t * ui_Screen3_Label16;
lv_obj_t * ui_Screen3_Button2;
lv_obj_t * ui_Screen3_Label2;
lv_obj_t * ui_Screen3_Roller1;
lv_obj_t * ui_Screen3_Button3;
lv_obj_t * ui_Screen3_Label3;
void ui_event_Screen3_Button14(lv_event_t * e);
lv_obj_t * ui_Screen3_Button14;
lv_obj_t * ui_Screen3_Label17;
lv_obj_t * ui_Screen3_Panel4;
lv_obj_t * ui_Screen3_Label18;
lv_obj_t * ui_Screen3_Panel6;
void ui_event_Screen3_Switch1(lv_event_t * e);
lv_obj_t * ui_Screen3_Switch1;
lv_obj_t * ui_Screen3_Label22;
lv_obj_t * ui_Screen3_Label23;
lv_obj_t * ui_Screen3_Label24;
void ui_event_Screen3_Switch3(lv_event_t * e);
lv_obj_t * ui_Screen3_Switch3;
lv_obj_t * ui_Screen3_Label5;
lv_obj_t * ui_Screen3_Label1;
lv_obj_t * ui_Screen3_Label6;
void ui_event_Screen3_Button15(lv_event_t * e);
lv_obj_t * ui_Screen3_Button15;
lv_obj_t * ui_Screen3_Label25;
lv_obj_t * ui_Screen3_Roller3;
lv_obj_t * ui_Screen3_Label26;
lv_obj_t * ui_Screen3_Label27;


// SCREEN: ui_Screen4
void ui_Screen4_screen_init(void);
lv_obj_t * ui_Screen4;


// SCREEN: ui_Screen5
void ui_Screen5_screen_init(void);
lv_obj_t * ui_Screen5;
lv_obj_t * ui_Screen4_Panel3;
lv_obj_t * ui_Screen4_Dropdown1;
lv_obj_t * ui_Screen4_Label13;
lv_obj_t * ui_Screen3_Roller9;
lv_obj_t * ui_Screen4_Panel6;
lv_obj_t * ui_Screen3_Roller12;
lv_obj_t * ui_Screen3_Roller13;
lv_obj_t * ui_Screen3_Roller14;
lv_obj_t * ui_Screen4_Label14;
lv_obj_t * ui_Screen4_Label15;
lv_obj_t * ui_Screen4_Label16;
lv_obj_t * ui_Screen4_Panel7;
lv_obj_t * ui_Screen3_Roller15;
lv_obj_t * ui_Screen3_Roller16;
lv_obj_t * ui_Screen3_Roller17;
lv_obj_t * ui_Screen4_Label17;
lv_obj_t * ui_Screen4_Label18;
lv_obj_t * ui_Screen4_Label19;
lv_obj_t * ui_Screen4_Panel8;
lv_obj_t * ui_Screen4_Label20;
lv_obj_t * ui_Screen4_Label21;
lv_obj_t * ui_Screen4_Label22;
void ui_event_Screen3_Switch2(lv_event_t * e);
lv_obj_t * ui_Screen3_Switch2;
lv_obj_t * ui_Screen3_Label13;
lv_obj_t * ui_Screen3_Label19;
void ui_event_Screen3_Switch8(lv_event_t * e);
lv_obj_t * ui_Screen3_Switch8;
lv_obj_t * ui_Screen3_Label20;
lv_obj_t * ui_Screen3_Label21;
void ui_event_Screen3_Switch9(lv_event_t * e);
lv_obj_t * ui_Screen3_Switch9;
lv_obj_t * ui_Screen3_Label28;
lv_obj_t * ui_Screen3_Label29;
void ui_event_Screen3_Switch10(lv_event_t * e);
lv_obj_t * ui_Screen3_Switch10;
lv_obj_t * ui_Screen3_Label30;
lv_obj_t * ui_Screen3_Label31;
lv_obj_t * ui_Screen4_Label23;
lv_obj_t * ui_Screen3_Roller18;
lv_obj_t * ui_Screen4_Label24;
void ui_event_Screen3_Button1(lv_event_t * e);
lv_obj_t * ui_Screen3_Button1;
lv_obj_t * ui_Screen3_Label32;


// SCREEN: ui_Screen6
void ui_Screen6_screen_init(void);
lv_obj_t * ui_Screen6;
lv_obj_t * ui_Screen6_Button4;
lv_obj_t * ui_Screen3_Label4;
lv_obj_t * ui_Screen6_Button5;
lv_obj_t * ui_Screen3_Label7;
lv_obj_t * ui_Screen6_Roller2;
lv_obj_t * ui_Screen6_Button6;
lv_obj_t * ui_Screen3_Label8;
void ui_event_Screen3_Button7(lv_event_t * e);
lv_obj_t * ui_Screen3_Button7;
lv_obj_t * ui_Screen3_Label9;
lv_obj_t * ui_Screen6_Panel1;
lv_obj_t * ui_Screen3_Label10;
lv_obj_t * ui_Screen6_Panel2;
void ui_event_Screen6_Switch4(lv_event_t * e);
lv_obj_t * ui_Screen6_Switch4;
lv_obj_t * ui_Screen6_Label11;
lv_obj_t * ui_Screen6_Label12;
lv_obj_t * ui_Screen3_Label14;
void ui_event_Screen6_Switch5(lv_event_t * e);
lv_obj_t * ui_Screen6_Switch5;
lv_obj_t * ui_Screen6_Label15;
lv_obj_t * ui_Screen6_Label33;
lv_obj_t * ui_Screen3_Label34;
void ui_event_Screen6_Button8(lv_event_t * e);
lv_obj_t * ui_Screen6_Button8;
lv_obj_t * ui_Screen3_Label35;
lv_obj_t * ui_Screen6_Roller4;
lv_obj_t * ui_Screen6_Label36;
lv_obj_t * ui_Screen6_Label37;
lv_obj_t * ui____initial_actions0;

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////
void ui_event_Screen1_Button5(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen3, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Screen3_screen_init);
    }
}
void ui_event_Screen1_Button2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen6, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Screen6_screen_init);
    }
}
void ui_event_Screen1_Button7(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen2, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Screen2_screen_init);
    }
}
void ui_event_Screen2_Button11(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_Screen2_Keyboard1, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_TOGGLE);
    }
}
void ui_event_Screen2_TextArea2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_keyboard_set_target(ui_Screen2_Keyboard1,  ui_Screen2_TextArea2);
    }
    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_Screen2_Keyboard1, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_TOGGLE);
    }
}
void ui_event_Screen2_Button12(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen1, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Screen1_screen_init);
    }
}
void ui_event_Screen2_Label15(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen1, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Screen1_screen_init);
    }
}
void ui_event_Screen3_Button14(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen1, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Screen1_screen_init);
    }
}
void ui_event_Screen3_Switch1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_Screen3_Label22, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_TOGGLE);
        _ui_flag_modify(ui_Screen3_Label23, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_TOGGLE);
    }
}
void ui_event_Screen3_Switch3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_Screen3_Label5, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_TOGGLE);
        _ui_flag_modify(ui_Screen3_Label1, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_TOGGLE);
        _ui_flag_modify(ui_Screen3_Label26, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_TOGGLE);
        _ui_flag_modify(ui_Screen3_Roller3, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_TOGGLE);
    }
}
void ui_event_Screen3_Button15(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen4, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Screen4_screen_init);
    }
}
void ui_event_Screen3_Switch2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_Screen3_Label4, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_TOGGLE);
        _ui_flag_modify(ui_Screen3_Label8, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_TOGGLE);
    }
}
void ui_event_Screen3_Switch8(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_Screen3_Label7, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_TOGGLE);
        _ui_flag_modify(ui_Screen3_Label10, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_TOGGLE);
    }
}
void ui_event_Screen3_Switch9(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_Screen3_Label12, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_TOGGLE);
        _ui_flag_modify(ui_Screen3_Label11, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_TOGGLE);
    }
}
void ui_event_Screen3_Switch10(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_Screen4_Label12, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_TOGGLE);
        _ui_flag_modify(ui_Screen3_Roller11, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_TOGGLE);
        _ui_flag_modify(ui_Screen3_Label14, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_TOGGLE);
        _ui_flag_modify(ui_Screen3_Label9, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_TOGGLE);
    }
}
void ui_event_Screen3_Button1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen1, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Screen1_screen_init);
    }
}
void ui_event_Screen3_Button7(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen1, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Screen1_screen_init);
    }
}
void ui_event_Screen6_Switch4(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_Screen3_Label22, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_TOGGLE);
        _ui_flag_modify(ui_Screen3_Label23, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_TOGGLE);
    }
}
void ui_event_Screen6_Switch5(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_Screen3_Label5, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_TOGGLE);
        _ui_flag_modify(ui_Screen3_Label1, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_TOGGLE);
        _ui_flag_modify(ui_Screen3_Label26, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_TOGGLE);
        _ui_flag_modify(ui_Screen3_Roller3, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_TOGGLE);
    }
}
void ui_event_Screen6_Button8(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen4, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Screen4_screen_init);
    }
}

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    lv_disp_t * dispp = lv_disp_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               false, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_Screen1_screen_init();
    ui_Screen2_screen_init();
    ui_Screen3_screen_init();
    ui_Screen4_screen_init();
    ui_Screen5_screen_init();
    ui_Screen6_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_Screen1);
}
