// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
#if __has_include("lvgl.h")
#include "lvgl.h"
#elif __has_include("lvgl/lvgl.h")
#include "lvgl/lvgl.h"
#else
#include "lvgl.h"
#endif
#else
#include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_events.h"

// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
extern lv_obj_t * ui_Screen1;
void ui_event_Screen1_Arc1(lv_event_t * e);
extern lv_obj_t * ui_Screen1_Arc1;
void ui_event_Screen1_Button2(lv_event_t * e);
extern lv_obj_t * ui_Screen1_Button2;
extern lv_obj_t * ui_Screen1_Label1;
extern lv_obj_t * ui_Screen1_Label11;
void ui_event_Screen1_Button7(lv_event_t * e);
extern lv_obj_t * ui_Screen1_Button7;
extern lv_obj_t * ui_Screen1_Label10;
void ui_event_Screen1_Arc2(lv_event_t * e);
extern lv_obj_t * ui_Screen1_Arc2;
extern lv_obj_t * ui_Screen1_Label8;
extern lv_obj_t * ui_Screen1_Button4;
extern lv_obj_t * ui_Screen1_Label6;
extern lv_obj_t * ui_Screen1_Label9;
void ui_event_Screen1_Button3(lv_event_t * e);
extern lv_obj_t * ui_Screen1_Button3;
extern lv_obj_t * ui_Screen1_Label3;
extern lv_obj_t * ui_Screen1_Label2;
// SCREEN: ui_Screen2
void ui_Screen2_screen_init(void);
extern lv_obj_t * ui_Screen2;
extern lv_obj_t * ui_Screen2_Dropdown2;
extern lv_obj_t * ui_Screen2_Button8;
extern lv_obj_t * ui_Screen2_Label11;
extern lv_obj_t * ui_Screen2_Button9;
extern lv_obj_t * ui_Screen2_Label12;
extern lv_obj_t * ui_Screen2_Button10;
extern lv_obj_t * ui_Screen2_Label13;
extern lv_obj_t * ui_Screen2_Panel3;
extern lv_obj_t * ui_Screen2_Label5;
extern lv_obj_t * ui_Screen2_Label6;
extern lv_obj_t * ui_Screen2_Label7;
void ui_event_Screen2_TextArea2(lv_event_t * e);
extern lv_obj_t * ui_Screen2_TextArea2;
extern lv_obj_t * ui_Screen2_Keyboard1;
void ui_event_Screen2_Button11(lv_event_t * e);
extern lv_obj_t * ui_Screen2_Button11;
extern lv_obj_t * ui_Screen2_Label14;
void ui_event_Screen2_Button12(lv_event_t * e);
extern lv_obj_t * ui_Screen2_Button12;
void ui_event_Screen2_Label15(lv_event_t * e);
extern lv_obj_t * ui_Screen2_Label15;
// SCREEN: ui_Screen3
void ui_Screen3_screen_init(void);
extern lv_obj_t * ui_Screen3;
extern lv_obj_t * ui_Screen3_Button13;
extern lv_obj_t * ui_Screen3_Label16;
extern lv_obj_t * ui_Screen3_Button2;
extern lv_obj_t * ui_Screen3_Label2;
extern lv_obj_t * ui_Screen3_Roller1;
extern lv_obj_t * ui_Screen3_Button3;
extern lv_obj_t * ui_Screen3_Label3;
void ui_event_Screen3_Button14(lv_event_t * e);
extern lv_obj_t * ui_Screen3_Button14;
extern lv_obj_t * ui_Screen3_Label17;
extern lv_obj_t * ui_Screen3_Panel4;
extern lv_obj_t * ui_Screen3_Label18;
extern lv_obj_t * ui_Screen3_Panel6;
void ui_event_Screen3_Switch1(lv_event_t * e);
extern lv_obj_t * ui_Screen3_Switch1;
extern lv_obj_t * ui_Screen3_Label22;
extern lv_obj_t * ui_Screen3_Label23;
extern lv_obj_t * ui_Screen3_Label24;
void ui_event_Screen3_Switch3(lv_event_t * e);
extern lv_obj_t * ui_Screen3_Switch3;
extern lv_obj_t * ui_Screen3_Label5;
extern lv_obj_t * ui_Screen3_Label1;
extern lv_obj_t * ui_Screen3_Label6;
void ui_event_Screen3_Button15(lv_event_t * e);
extern lv_obj_t * ui_Screen3_Button15;
extern lv_obj_t * ui_Screen3_Label25;
extern lv_obj_t * ui_Screen3_Roller3;
extern lv_obj_t * ui_Screen3_Label26;
extern lv_obj_t * ui_Screen3_Label27;
extern lv_obj_t * ui_Screen3_Dropdown1;
extern lv_obj_t * ui_Screen3_Label12;
// SCREEN: ui_Screen5
void ui_Screen5_screen_init(void);
extern lv_obj_t * ui_Screen5;
extern lv_obj_t * ui_Screen4_Panel3;
extern lv_obj_t * ui_Screen4_Dropdown1;
extern lv_obj_t * ui_Screen4_Label13;
extern lv_obj_t * ui_Screen3_Roller9;
extern lv_obj_t * ui_Screen4_Panel6;
extern lv_obj_t * ui_Screen3_Roller12;
extern lv_obj_t * ui_Screen3_Roller13;
extern lv_obj_t * ui_Screen3_Roller14;
extern lv_obj_t * ui_Screen4_Label14;
extern lv_obj_t * ui_Screen4_Label15;
extern lv_obj_t * ui_Screen4_Label16;
extern lv_obj_t * ui_Screen4_Panel7;
extern lv_obj_t * ui_Screen3_Roller15;
extern lv_obj_t * ui_Screen3_Roller16;
extern lv_obj_t * ui_Screen3_Roller17;
extern lv_obj_t * ui_Screen4_Label17;
extern lv_obj_t * ui_Screen4_Label18;
extern lv_obj_t * ui_Screen4_Label19;
extern lv_obj_t * ui_Screen4_Panel8;
extern lv_obj_t * ui_Screen4_Label20;
extern lv_obj_t * ui_Screen4_Label21;
extern lv_obj_t * ui_Screen4_Label22;
void ui_event_Screen3_Switch2(lv_event_t * e);
extern lv_obj_t * ui_Screen3_Switch2;
extern lv_obj_t * ui_Screen3_Label13;
extern lv_obj_t * ui_Screen3_Label19;
void ui_event_Screen3_Switch8(lv_event_t * e);
extern lv_obj_t * ui_Screen3_Switch8;
extern lv_obj_t * ui_Screen3_Label20;
extern lv_obj_t * ui_Screen3_Label21;
void ui_event_Screen3_Switch9(lv_event_t * e);
extern lv_obj_t * ui_Screen3_Switch9;
extern lv_obj_t * ui_Screen3_Label28;
extern lv_obj_t * ui_Screen3_Label29;
void ui_event_Screen3_Switch10(lv_event_t * e);
extern lv_obj_t * ui_Screen3_Switch10;
extern lv_obj_t * ui_Screen3_Label30;
extern lv_obj_t * ui_Screen3_Label31;
extern lv_obj_t * ui_Screen4_Label23;
extern lv_obj_t * ui_Screen3_Roller18;
extern lv_obj_t * ui_Screen4_Label24;
void ui_event_Screen3_Button1(lv_event_t * e);
extern lv_obj_t * ui_Screen3_Button1;
extern lv_obj_t * ui_Screen3_Label32;
extern lv_obj_t * ui_Screen5_Button3;
extern lv_obj_t * ui_Screen5_Label13;
extern lv_obj_t * ui____initial_actions0;


LV_IMG_DECLARE(ui_img_1863159612);    // assets/gradient-linear-purple-green-800x480-c2-8b008b-008080-a-45-f-14.png






void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
