// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

void ui_Screen2_screen_init(void)
{
    ui_Screen2 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Screen2, lv_color_hex(0xA91D3A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Screen2_Dropdown2 = lv_dropdown_create(ui_Screen2);
    lv_obj_set_width(ui_Screen2_Dropdown2, 268);
    lv_obj_set_height(ui_Screen2_Dropdown2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Screen2_Dropdown2, -190);
    lv_obj_set_y(ui_Screen2_Dropdown2, -158);
    lv_obj_set_align(ui_Screen2_Dropdown2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Screen2_Dropdown2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags



    ui_Screen2_Button8 = lv_btn_create(ui_Screen2);
    lv_obj_set_width(ui_Screen2_Button8, 119);
    lv_obj_set_height(ui_Screen2_Button8, 57);
    lv_obj_set_x(ui_Screen2_Button8, -269);
    lv_obj_set_y(ui_Screen2_Button8, -92);
    lv_obj_set_align(ui_Screen2_Button8, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Screen2_Button8, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Screen2_Button8, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Screen2_Button8, lv_color_hex(0x151515), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen2_Button8, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_Screen2_Button8, lv_color_hex(0x394C83), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Screen2_Button8, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Screen2_Label11 = lv_label_create(ui_Screen2_Button8);
    lv_obj_set_width(ui_Screen2_Label11, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Screen2_Label11, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Screen2_Label11, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Screen2_Label11, "SCAN");
    lv_obj_set_style_text_font(ui_Screen2_Label11, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Screen2_Button9 = lv_btn_create(ui_Screen2);
    lv_obj_set_width(ui_Screen2_Button9, 117);
    lv_obj_set_height(ui_Screen2_Button9, 60);
    lv_obj_set_x(ui_Screen2_Button9, -112);
    lv_obj_set_y(ui_Screen2_Button9, -93);
    lv_obj_set_align(ui_Screen2_Button9, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Screen2_Button9, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Screen2_Button9, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Screen2_Button9, lv_color_hex(0x151515), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen2_Button9, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_Screen2_Button9, lv_color_hex(0x940400), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Screen2_Button9, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Screen2_Label12 = lv_label_create(ui_Screen2_Button9);
    lv_obj_set_width(ui_Screen2_Label12, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Screen2_Label12, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Screen2_Label12, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Screen2_Label12, "CONNECT");
    lv_obj_set_style_text_font(ui_Screen2_Label12, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Screen2_Button10 = lv_btn_create(ui_Screen2);
    lv_obj_set_width(ui_Screen2_Button10, 283);
    lv_obj_set_height(ui_Screen2_Button10, 104);
    lv_obj_set_x(ui_Screen2_Button10, -195);
    lv_obj_set_y(ui_Screen2_Button10, 8);
    lv_obj_set_align(ui_Screen2_Button10, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Screen2_Button10, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Screen2_Button10, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Screen2_Button10, lv_color_hex(0x151515), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen2_Button10, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_Screen2_Button10, lv_color_hex(0x186583), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Screen2_Button10, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Screen2_Label13 = lv_label_create(ui_Screen2_Button10);
    lv_obj_set_width(ui_Screen2_Label13, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Screen2_Label13, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Screen2_Label13, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Screen2_Label13, "CHECK FOR UPDATE");
    lv_obj_set_style_text_font(ui_Screen2_Label13, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Screen2_Panel3 = lv_obj_create(ui_Screen2);
    lv_obj_set_width(ui_Screen2_Panel3, 316);
    lv_obj_set_height(ui_Screen2_Panel3, 232);
    lv_obj_set_x(ui_Screen2_Panel3, 181);
    lv_obj_set_y(ui_Screen2_Panel3, -63);
    lv_obj_set_align(ui_Screen2_Panel3, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Screen2_Panel3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Screen2_Panel3, lv_color_hex(0x151515), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen2_Panel3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Screen2_Label5 = lv_label_create(ui_Screen2_Panel3);
    lv_obj_set_width(ui_Screen2_Label5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Screen2_Label5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Screen2_Label5, -115);
    lv_obj_set_y(ui_Screen2_Label5, -7);
    lv_obj_set_align(ui_Screen2_Label5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Screen2_Label5, "LOGS");
    lv_obj_set_style_text_color(ui_Screen2_Label5, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Screen2_Label5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Screen2_Label6 = lv_label_create(ui_Screen2_Panel3);
    lv_obj_set_width(ui_Screen2_Label6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Screen2_Label6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Screen2_Label6, -3);
    lv_obj_set_y(ui_Screen2_Label6, -4);
    lv_obj_set_align(ui_Screen2_Label6, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Screen2_Label6, "__________________________________________");
    lv_obj_set_style_text_color(ui_Screen2_Label6, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Screen2_Label6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Screen2_Label7 = lv_label_create(ui_Screen2_Panel3);
    lv_obj_set_width(ui_Screen2_Label7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Screen2_Label7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Screen2_Label7, -4);
    lv_obj_set_y(ui_Screen2_Label7, 32);
    lv_obj_set_align(ui_Screen2_Label7, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Screen2_Label7, "LOG MESSAGE");
    lv_obj_set_style_text_color(ui_Screen2_Label7, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Screen2_Label7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Screen2_Label7, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Screen2_TextArea2 = lv_textarea_create(ui_Screen2_Panel3);
    lv_obj_set_width(ui_Screen2_TextArea2, 262);
    lv_obj_set_height(ui_Screen2_TextArea2, 70);
    lv_obj_set_x(ui_Screen2_TextArea2, 3);
    lv_obj_set_y(ui_Screen2_TextArea2, -60);
    lv_obj_set_align(ui_Screen2_TextArea2, LV_ALIGN_CENTER);
    lv_textarea_set_placeholder_text(ui_Screen2_TextArea2, "Enter WIFI password here");



    ui_Screen2_Keyboard1 = lv_keyboard_create(ui_Screen2);
    lv_obj_set_width(ui_Screen2_Keyboard1, 797);
    lv_obj_set_height(ui_Screen2_Keyboard1, 215);
    lv_obj_set_x(ui_Screen2_Keyboard1, -1);
    lv_obj_set_y(ui_Screen2_Keyboard1, 131);
    lv_obj_set_align(ui_Screen2_Keyboard1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Screen2_Keyboard1, LV_OBJ_FLAG_HIDDEN);     /// Flags

    ui_Screen2_Button11 = lv_btn_create(ui_Screen2_Keyboard1);
    lv_obj_set_width(ui_Screen2_Button11, 100);
    lv_obj_set_height(ui_Screen2_Button11, 50);
    lv_obj_set_x(ui_Screen2_Button11, 335);
    lv_obj_set_y(ui_Screen2_Button11, 72);
    lv_obj_set_align(ui_Screen2_Button11, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Screen2_Button11, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Screen2_Button11, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Screen2_Label14 = lv_label_create(ui_Screen2_Button11);
    lv_obj_set_width(ui_Screen2_Label14, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Screen2_Label14, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Screen2_Label14, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Screen2_Label14, "DONE");

    ui_Screen2_Button12 = lv_btn_create(ui_Screen2);
    lv_obj_set_width(ui_Screen2_Button12, 114);
    lv_obj_set_height(ui_Screen2_Button12, 50);
    lv_obj_set_x(ui_Screen2_Button12, 328);
    lv_obj_set_y(ui_Screen2_Button12, -211);
    lv_obj_set_align(ui_Screen2_Button12, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Screen2_Button12, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Screen2_Button12, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Screen2_Button12, lv_color_hex(0x151515), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen2_Button12, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Screen2_Button12, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Screen2_Label15 = lv_label_create(ui_Screen2_Button12);
    lv_obj_set_width(ui_Screen2_Label15, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Screen2_Label15, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Screen2_Label15, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Screen2_Label15, "BACK TO\nMAIN MENU");

    lv_obj_add_event_cb(ui_Screen2_TextArea2, ui_event_Screen2_TextArea2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Screen2_Button11, ui_event_Screen2_Button11, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Screen2_Label15, ui_event_Screen2_Label15, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Screen2_Button12, ui_event_Screen2_Button12, LV_EVENT_ALL, NULL);

}
