// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

void ui_Screen5_screen_init(void)
{
    ui_Screen5 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Screen5, lv_color_hex(0x1F0675), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Screen4_Panel3 = lv_obj_create(ui_Screen5);
    lv_obj_set_width(ui_Screen4_Panel3, 186);
    lv_obj_set_height(ui_Screen4_Panel3, 213);
    lv_obj_set_x(ui_Screen4_Panel3, -245);
    lv_obj_set_y(ui_Screen4_Panel3, -112);
    lv_obj_set_align(ui_Screen4_Panel3, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Screen4_Panel3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Screen4_Panel3, lv_color_hex(0x151515), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen4_Panel3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Screen4_Dropdown1 = lv_dropdown_create(ui_Screen4_Panel3);
    lv_dropdown_set_options(ui_Screen4_Dropdown1, "PROGRAM 1\nPROGRAM 2\nPROGRAM 3");
    lv_obj_set_width(ui_Screen4_Dropdown1, 150);
    lv_obj_set_height(ui_Screen4_Dropdown1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Screen4_Dropdown1, 2);
    lv_obj_set_y(ui_Screen4_Dropdown1, -68);
    lv_obj_set_align(ui_Screen4_Dropdown1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Screen4_Dropdown1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags



    ui_Screen4_Label13 = lv_label_create(ui_Screen4_Panel3);
    lv_obj_set_width(ui_Screen4_Label13, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Screen4_Label13, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Screen4_Label13, -16);
    lv_obj_set_y(ui_Screen4_Label13, -25);
    lv_obj_set_align(ui_Screen4_Label13, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Screen4_Label13, "START SPEED");
    lv_obj_set_style_text_color(ui_Screen4_Label13, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Screen4_Label13, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Screen3_Roller9 = lv_roller_create(ui_Screen4_Panel3);
    lv_roller_set_options(ui_Screen3_Roller9,
                          "10\n11\n12\n13\n14 \n15\n16\n17\n18\n19\n20\n21\n22\n23\n24\n25\n26\n27\n28\n29\n30\n31\n32\n33\n34\n35\n36\n37\n38\n39\n40\n41\n42\n43\n44\n45\n46\n47\n48\n49\n50\n51\n52\n53\n54\n55\n56\n57\n58\n59\n60",
                          LV_ROLLER_MODE_NORMAL);
    lv_obj_set_width(ui_Screen3_Roller9, 145);
    lv_obj_set_height(ui_Screen3_Roller9, 108);
    lv_obj_set_x(ui_Screen3_Roller9, 1);
    lv_obj_set_y(ui_Screen3_Roller9, 42);
    lv_obj_set_align(ui_Screen3_Roller9, LV_ALIGN_CENTER);
    lv_obj_set_style_text_color(ui_Screen3_Roller9, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Screen3_Roller9, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Screen3_Roller9, lv_color_hex(0x151515), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen3_Roller9, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_Screen3_Roller9, lv_color_hex(0x0824B3), LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen3_Roller9, 255, LV_PART_SELECTED | LV_STATE_DEFAULT);

    ui_Screen4_Panel6 = lv_obj_create(ui_Screen5);
    lv_obj_set_width(ui_Screen4_Panel6, 429);
    lv_obj_set_height(ui_Screen4_Panel6, 137);
    lv_obj_set_x(ui_Screen4_Panel6, 66);
    lv_obj_set_y(ui_Screen4_Panel6, -150);
    lv_obj_set_align(ui_Screen4_Panel6, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Screen4_Panel6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Screen4_Panel6, lv_color_hex(0x151515), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen4_Panel6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Screen3_Roller12 = lv_roller_create(ui_Screen4_Panel6);
    lv_roller_set_options(ui_Screen3_Roller12,
                          "10\n11\n12\n13\n14 \n15\n16\n17\n18\n19\n20\n21\n22\n23\n24\n25\n26\n27\n28\n29\n30\n31\n32\n33\n34\n35\n36\n37\n38\n39\n40\n41\n42\n43\n44\n45\n46\n47\n48\n49\n50\n51\n52\n53\n54\n55\n56\n57\n58\n59\n60",
                          LV_ROLLER_MODE_NORMAL);
    lv_obj_set_width(ui_Screen3_Roller12, 130);
    lv_obj_set_height(ui_Screen3_Roller12, 70);
    lv_obj_set_x(ui_Screen3_Roller12, -137);
    lv_obj_set_y(ui_Screen3_Roller12, 12);
    lv_obj_set_align(ui_Screen3_Roller12, LV_ALIGN_CENTER);
    lv_obj_set_style_text_color(ui_Screen3_Roller12, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Screen3_Roller12, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Screen3_Roller12, lv_color_hex(0x151515), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen3_Roller12, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_Screen3_Roller12, lv_color_hex(0x0824B3), LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen3_Roller12, 255, LV_PART_SELECTED | LV_STATE_DEFAULT);

    ui_Screen3_Roller13 = lv_roller_create(ui_Screen4_Panel6);
    lv_roller_set_options(ui_Screen3_Roller13,
                          "10\n11\n12\n13\n14 \n15\n16\n17\n18\n19\n20\n21\n22\n23\n24\n25\n26\n27\n28\n29\n30\n31\n32\n33\n34\n35\n36\n37\n38\n39\n40\n41\n42\n43\n44\n45\n46\n47\n48\n49\n50\n51\n52\n53\n54\n55\n56\n57\n58\n59\n60",
                          LV_ROLLER_MODE_NORMAL);
    lv_obj_set_width(ui_Screen3_Roller13, 130);
    lv_obj_set_height(ui_Screen3_Roller13, 70);
    lv_obj_set_x(ui_Screen3_Roller13, 3);
    lv_obj_set_y(ui_Screen3_Roller13, 11);
    lv_obj_set_align(ui_Screen3_Roller13, LV_ALIGN_CENTER);
    lv_obj_set_style_text_color(ui_Screen3_Roller13, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Screen3_Roller13, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Screen3_Roller13, lv_color_hex(0x151515), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen3_Roller13, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_Screen3_Roller13, lv_color_hex(0x0824B3), LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen3_Roller13, 255, LV_PART_SELECTED | LV_STATE_DEFAULT);

    ui_Screen3_Roller14 = lv_roller_create(ui_Screen4_Panel6);
    lv_roller_set_options(ui_Screen3_Roller14,
                          "10\n11\n12\n13\n14 \n15\n16\n17\n18\n19\n20\n21\n22\n23\n24\n25\n26\n27\n28\n29\n30\n31\n32\n33\n34\n35\n36\n37\n38\n39\n40\n41\n42\n43\n44\n45\n46\n47\n48\n49\n50\n51\n52\n53\n54\n55\n56\n57\n58\n59\n60",
                          LV_ROLLER_MODE_NORMAL);
    lv_obj_set_width(ui_Screen3_Roller14, 130);
    lv_obj_set_height(ui_Screen3_Roller14, 70);
    lv_obj_set_x(ui_Screen3_Roller14, 142);
    lv_obj_set_y(ui_Screen3_Roller14, 11);
    lv_obj_set_align(ui_Screen3_Roller14, LV_ALIGN_CENTER);
    lv_obj_set_style_text_color(ui_Screen3_Roller14, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Screen3_Roller14, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Screen3_Roller14, lv_color_hex(0x151515), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen3_Roller14, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_Screen3_Roller14, lv_color_hex(0x0824B3), LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen3_Roller14, 255, LV_PART_SELECTED | LV_STATE_DEFAULT);

    ui_Screen4_Label14 = lv_label_create(ui_Screen4_Panel6);
    lv_obj_set_width(ui_Screen4_Label14, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Screen4_Label14, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Screen4_Label14, -169);
    lv_obj_set_y(ui_Screen4_Label14, -34);
    lv_obj_set_align(ui_Screen4_Label14, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Screen4_Label14, "TIME 1");
    lv_obj_set_style_text_color(ui_Screen4_Label14, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Screen4_Label14, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Screen4_Label15 = lv_label_create(ui_Screen4_Panel6);
    lv_obj_set_width(ui_Screen4_Label15, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Screen4_Label15, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Screen4_Label15, -30);
    lv_obj_set_y(ui_Screen4_Label15, -36);
    lv_obj_set_align(ui_Screen4_Label15, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Screen4_Label15, "TIME 2");
    lv_obj_set_style_text_color(ui_Screen4_Label15, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Screen4_Label15, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Screen4_Label16 = lv_label_create(ui_Screen4_Panel6);
    lv_obj_set_width(ui_Screen4_Label16, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Screen4_Label16, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Screen4_Label16, 111);
    lv_obj_set_y(ui_Screen4_Label16, -37);
    lv_obj_set_align(ui_Screen4_Label16, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Screen4_Label16, "TIME 3");
    lv_obj_set_style_text_color(ui_Screen4_Label16, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Screen4_Label16, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Screen4_Panel7 = lv_obj_create(ui_Screen5);
    lv_obj_set_width(ui_Screen4_Panel7, 429);
    lv_obj_set_height(ui_Screen4_Panel7, 153);
    lv_obj_set_x(ui_Screen4_Panel7, 67);
    lv_obj_set_y(ui_Screen4_Panel7, 2);
    lv_obj_set_align(ui_Screen4_Panel7, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Screen4_Panel7, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Screen4_Panel7, lv_color_hex(0x151515), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen4_Panel7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Screen3_Roller15 = lv_roller_create(ui_Screen4_Panel7);
    lv_roller_set_options(ui_Screen3_Roller15,
                          "10\n11\n12\n13\n14 \n15\n16\n17\n18\n19\n20\n21\n22\n23\n24\n25\n26\n27\n28\n29\n30\n31\n32\n33\n34\n35\n36\n37\n38\n39\n40\n41\n42\n43\n44\n45\n46\n47\n48\n49\n50\n51\n52\n53\n54\n55\n56\n57\n58\n59\n60",
                          LV_ROLLER_MODE_NORMAL);
    lv_obj_set_width(ui_Screen3_Roller15, 130);
    lv_obj_set_height(ui_Screen3_Roller15, 70);
    lv_obj_set_x(ui_Screen3_Roller15, -137);
    lv_obj_set_y(ui_Screen3_Roller15, 12);
    lv_obj_set_align(ui_Screen3_Roller15, LV_ALIGN_CENTER);
    lv_obj_set_style_text_color(ui_Screen3_Roller15, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Screen3_Roller15, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Screen3_Roller15, lv_color_hex(0x151515), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen3_Roller15, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_Screen3_Roller15, lv_color_hex(0x0824B3), LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen3_Roller15, 255, LV_PART_SELECTED | LV_STATE_DEFAULT);

    ui_Screen3_Roller16 = lv_roller_create(ui_Screen4_Panel7);
    lv_roller_set_options(ui_Screen3_Roller16,
                          "10\n11\n12\n13\n14 \n15\n16\n17\n18\n19\n20\n21\n22\n23\n24\n25\n26\n27\n28\n29\n30\n31\n32\n33\n34\n35\n36\n37\n38\n39\n40\n41\n42\n43\n44\n45\n46\n47\n48\n49\n50\n51\n52\n53\n54\n55\n56\n57\n58\n59\n60",
                          LV_ROLLER_MODE_NORMAL);
    lv_obj_set_width(ui_Screen3_Roller16, 130);
    lv_obj_set_height(ui_Screen3_Roller16, 70);
    lv_obj_set_x(ui_Screen3_Roller16, 3);
    lv_obj_set_y(ui_Screen3_Roller16, 11);
    lv_obj_set_align(ui_Screen3_Roller16, LV_ALIGN_CENTER);
    lv_obj_set_style_text_color(ui_Screen3_Roller16, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Screen3_Roller16, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Screen3_Roller16, lv_color_hex(0x151515), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen3_Roller16, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_Screen3_Roller16, lv_color_hex(0x0824B3), LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen3_Roller16, 255, LV_PART_SELECTED | LV_STATE_DEFAULT);

    ui_Screen3_Roller17 = lv_roller_create(ui_Screen4_Panel7);
    lv_roller_set_options(ui_Screen3_Roller17,
                          "10\n11\n12\n13\n14 \n15\n16\n17\n18\n19\n20\n21\n22\n23\n24\n25\n26\n27\n28\n29\n30\n31\n32\n33\n34\n35\n36\n37\n38\n39\n40\n41\n42\n43\n44\n45\n46\n47\n48\n49\n50\n51\n52\n53\n54\n55\n56\n57\n58\n59\n60",
                          LV_ROLLER_MODE_NORMAL);
    lv_obj_set_width(ui_Screen3_Roller17, 130);
    lv_obj_set_height(ui_Screen3_Roller17, 70);
    lv_obj_set_x(ui_Screen3_Roller17, 142);
    lv_obj_set_y(ui_Screen3_Roller17, 11);
    lv_obj_set_align(ui_Screen3_Roller17, LV_ALIGN_CENTER);
    lv_obj_set_style_text_color(ui_Screen3_Roller17, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Screen3_Roller17, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Screen3_Roller17, lv_color_hex(0x151515), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen3_Roller17, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_Screen3_Roller17, lv_color_hex(0x0824B3), LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen3_Roller17, 255, LV_PART_SELECTED | LV_STATE_DEFAULT);

    ui_Screen4_Label17 = lv_label_create(ui_Screen4_Panel7);
    lv_obj_set_width(ui_Screen4_Label17, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Screen4_Label17, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Screen4_Label17, -169);
    lv_obj_set_y(ui_Screen4_Label17, -34);
    lv_obj_set_align(ui_Screen4_Label17, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Screen4_Label17, "SPEED 1");
    lv_obj_set_style_text_color(ui_Screen4_Label17, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Screen4_Label17, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Screen4_Label18 = lv_label_create(ui_Screen4_Panel7);
    lv_obj_set_width(ui_Screen4_Label18, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Screen4_Label18, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Screen4_Label18, -30);
    lv_obj_set_y(ui_Screen4_Label18, -36);
    lv_obj_set_align(ui_Screen4_Label18, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Screen4_Label18, "SPEED 2");
    lv_obj_set_style_text_color(ui_Screen4_Label18, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Screen4_Label18, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Screen4_Label19 = lv_label_create(ui_Screen4_Panel7);
    lv_obj_set_width(ui_Screen4_Label19, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Screen4_Label19, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Screen4_Label19, 111);
    lv_obj_set_y(ui_Screen4_Label19, -37);
    lv_obj_set_align(ui_Screen4_Label19, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Screen4_Label19, "SPEED 3");
    lv_obj_set_style_text_color(ui_Screen4_Label19, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Screen4_Label19, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Screen4_Panel8 = lv_obj_create(ui_Screen5);
    lv_obj_set_width(ui_Screen4_Panel8, 429);
    lv_obj_set_height(ui_Screen4_Panel8, 143);
    lv_obj_set_x(ui_Screen4_Panel8, 66);
    lv_obj_set_y(ui_Screen4_Panel8, 154);
    lv_obj_set_align(ui_Screen4_Panel8, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Screen4_Panel8, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Screen4_Panel8, lv_color_hex(0x151515), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen4_Panel8, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Screen4_Label20 = lv_label_create(ui_Screen4_Panel8);
    lv_obj_set_width(ui_Screen4_Label20, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Screen4_Label20, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Screen4_Label20, -148);
    lv_obj_set_y(ui_Screen4_Label20, -25);
    lv_obj_set_align(ui_Screen4_Label20, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Screen4_Label20, "DIRECTION 1");
    lv_obj_set_style_text_color(ui_Screen4_Label20, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Screen4_Label20, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Screen4_Label21 = lv_label_create(ui_Screen4_Panel8);
    lv_obj_set_width(ui_Screen4_Label21, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Screen4_Label21, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Screen4_Label21, -10);
    lv_obj_set_y(ui_Screen4_Label21, -25);
    lv_obj_set_align(ui_Screen4_Label21, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Screen4_Label21, "DIRECTION 2");
    lv_obj_set_style_text_color(ui_Screen4_Label21, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Screen4_Label21, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Screen4_Label22 = lv_label_create(ui_Screen4_Panel8);
    lv_obj_set_width(ui_Screen4_Label22, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Screen4_Label22, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Screen4_Label22, 126);
    lv_obj_set_y(ui_Screen4_Label22, -28);
    lv_obj_set_align(ui_Screen4_Label22, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Screen4_Label22, "DIRECTION 3");
    lv_obj_set_style_text_color(ui_Screen4_Label22, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Screen4_Label22, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Screen3_Switch2 = lv_switch_create(ui_Screen4_Panel8);
    lv_obj_set_width(ui_Screen3_Switch2, 122);
    lv_obj_set_height(ui_Screen3_Switch2, 40);
    lv_obj_set_x(ui_Screen3_Switch2, -142);
    lv_obj_set_y(ui_Screen3_Switch2, 11);
    lv_obj_set_align(ui_Screen3_Switch2, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_Screen3_Switch2, lv_color_hex(0x3C4483), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen3_Switch2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Screen3_Switch2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Screen3_Switch2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Screen3_Switch2, 2, LV_PART_MAIN | LV_STATE_DEFAULT);


    ui_Screen3_Label13 = lv_label_create(ui_Screen3_Switch2);
    lv_obj_set_width(ui_Screen3_Label13, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Screen3_Label13, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Screen3_Label13, 15);
    lv_obj_set_y(ui_Screen3_Label13, 1);
    lv_obj_set_align(ui_Screen3_Label13, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Screen3_Label13, "FORWARD");
    lv_obj_set_style_text_color(ui_Screen3_Label13, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Screen3_Label13, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Screen3_Label19 = lv_label_create(ui_Screen3_Switch2);
    lv_obj_set_width(ui_Screen3_Label19, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Screen3_Label19, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Screen3_Label19, -3);
    lv_obj_set_y(ui_Screen3_Label19, 0);
    lv_obj_set_align(ui_Screen3_Label19, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Screen3_Label19, "BACK");
    lv_obj_add_flag(ui_Screen3_Label19, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_set_style_text_color(ui_Screen3_Label19, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Screen3_Label19, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Screen3_Switch8 = lv_switch_create(ui_Screen4_Panel8);
    lv_obj_set_width(ui_Screen3_Switch8, 122);
    lv_obj_set_height(ui_Screen3_Switch8, 40);
    lv_obj_set_x(ui_Screen3_Switch8, -12);
    lv_obj_set_y(ui_Screen3_Switch8, 11);
    lv_obj_set_align(ui_Screen3_Switch8, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_Screen3_Switch8, lv_color_hex(0x414483), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen3_Switch8, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Screen3_Switch8, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Screen3_Switch8, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Screen3_Switch8, 2, LV_PART_MAIN | LV_STATE_DEFAULT);


    ui_Screen3_Label20 = lv_label_create(ui_Screen3_Switch8);
    lv_obj_set_width(ui_Screen3_Label20, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Screen3_Label20, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Screen3_Label20, 15);
    lv_obj_set_y(ui_Screen3_Label20, 1);
    lv_obj_set_align(ui_Screen3_Label20, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Screen3_Label20, "FORWARD");
    lv_obj_set_style_text_color(ui_Screen3_Label20, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Screen3_Label20, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Screen3_Label21 = lv_label_create(ui_Screen3_Switch8);
    lv_obj_set_width(ui_Screen3_Label21, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Screen3_Label21, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Screen3_Label21, -3);
    lv_obj_set_y(ui_Screen3_Label21, 1);
    lv_obj_set_align(ui_Screen3_Label21, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Screen3_Label21, "BACK");
    lv_obj_add_flag(ui_Screen3_Label21, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_set_style_text_color(ui_Screen3_Label21, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Screen3_Label21, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Screen3_Switch9 = lv_switch_create(ui_Screen5);
    lv_obj_set_width(ui_Screen3_Switch9, 122);
    lv_obj_set_height(ui_Screen3_Switch9, 40);
    lv_obj_set_x(ui_Screen3_Switch9, 189);
    lv_obj_set_y(ui_Screen3_Switch9, 163);
    lv_obj_set_align(ui_Screen3_Switch9, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_Screen3_Switch9, lv_color_hex(0x413D83), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen3_Switch9, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Screen3_Switch9, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Screen3_Switch9, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Screen3_Switch9, 2, LV_PART_MAIN | LV_STATE_DEFAULT);


    ui_Screen3_Label28 = lv_label_create(ui_Screen3_Switch9);
    lv_obj_set_width(ui_Screen3_Label28, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Screen3_Label28, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Screen3_Label28, 15);
    lv_obj_set_y(ui_Screen3_Label28, 1);
    lv_obj_set_align(ui_Screen3_Label28, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Screen3_Label28, "FORWARD");
    lv_obj_set_style_text_color(ui_Screen3_Label28, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Screen3_Label28, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Screen3_Label29 = lv_label_create(ui_Screen3_Switch9);
    lv_obj_set_width(ui_Screen3_Label29, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Screen3_Label29, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Screen3_Label29, -5);
    lv_obj_set_y(ui_Screen3_Label29, 0);
    lv_obj_set_align(ui_Screen3_Label29, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Screen3_Label29, "BACK");
    lv_obj_add_flag(ui_Screen3_Label29, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_set_style_text_color(ui_Screen3_Label29, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Screen3_Label29, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Screen3_Switch10 = lv_switch_create(ui_Screen5);
    lv_obj_set_width(ui_Screen3_Switch10, 122);
    lv_obj_set_height(ui_Screen3_Switch10, 40);
    lv_obj_set_x(ui_Screen3_Switch10, -247);
    lv_obj_set_y(ui_Screen3_Switch10, 45);
    lv_obj_set_align(ui_Screen3_Switch10, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_Screen3_Switch10, lv_color_hex(0x315083), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen3_Switch10, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Screen3_Switch10, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Screen3_Switch10, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Screen3_Switch10, 2, LV_PART_MAIN | LV_STATE_DEFAULT);


    ui_Screen3_Label30 = lv_label_create(ui_Screen3_Switch10);
    lv_obj_set_width(ui_Screen3_Label30, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Screen3_Label30, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Screen3_Label30, 15);
    lv_obj_set_y(ui_Screen3_Label30, 1);
    lv_obj_set_align(ui_Screen3_Label30, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Screen3_Label30, "NO");
    lv_obj_set_style_text_color(ui_Screen3_Label30, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Screen3_Label30, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Screen3_Label31 = lv_label_create(ui_Screen3_Switch10);
    lv_obj_set_width(ui_Screen3_Label31, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Screen3_Label31, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Screen3_Label31, -5);
    lv_obj_set_y(ui_Screen3_Label31, 0);
    lv_obj_set_align(ui_Screen3_Label31, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Screen3_Label31, "YES");
    lv_obj_add_flag(ui_Screen3_Label31, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_set_style_text_color(ui_Screen3_Label31, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Screen3_Label31, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Screen4_Label23 = lv_label_create(ui_Screen5);
    lv_obj_set_width(ui_Screen4_Label23, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Screen4_Label23, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Screen4_Label23, -246);
    lv_obj_set_y(ui_Screen4_Label23, 12);
    lv_obj_set_align(ui_Screen4_Label23, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Screen4_Label23, "REPEAT THE PROGRAM?");
    lv_obj_set_style_text_color(ui_Screen4_Label23, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Screen4_Label23, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Screen3_Roller18 = lv_roller_create(ui_Screen5);
    lv_roller_set_options(ui_Screen3_Roller18, "1\n2\n3\n4\n5", LV_ROLLER_MODE_NORMAL);
    lv_obj_set_width(ui_Screen3_Roller18, 130);
    lv_obj_set_height(ui_Screen3_Roller18, 70);
    lv_obj_set_x(ui_Screen3_Roller18, -246);
    lv_obj_set_y(ui_Screen3_Roller18, 129);
    lv_obj_set_align(ui_Screen3_Roller18, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Screen3_Roller18, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_set_style_text_color(ui_Screen3_Roller18, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Screen3_Roller18, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Screen3_Roller18, lv_color_hex(0x186283), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen3_Roller18, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_Screen3_Roller18, lv_color_hex(0x0824B3), LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen3_Roller18, 255, LV_PART_SELECTED | LV_STATE_DEFAULT);

    ui_Screen4_Label24 = lv_label_create(ui_Screen5);
    lv_obj_set_width(ui_Screen4_Label24, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Screen4_Label24, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Screen4_Label24, -281);
    lv_obj_set_y(ui_Screen4_Label24, 82);
    lv_obj_set_align(ui_Screen4_Label24, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Screen4_Label24, "TIMES");
    lv_obj_add_flag(ui_Screen4_Label24, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_set_style_text_color(ui_Screen4_Label24, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Screen4_Label24, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Screen3_Button1 = lv_btn_create(ui_Screen5);
    lv_obj_set_width(ui_Screen3_Button1, 115);
    lv_obj_set_height(ui_Screen3_Button1, 50);
    lv_obj_set_x(ui_Screen3_Button1, 341);
    lv_obj_set_y(ui_Screen3_Button1, -214);
    lv_obj_set_align(ui_Screen3_Button1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Screen3_Button1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Screen3_Button1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Screen3_Button1, lv_color_hex(0x151515), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen3_Button1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Screen3_Button1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Screen3_Button1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Screen3_Button1, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Screen3_Label32 = lv_label_create(ui_Screen3_Button1);
    lv_obj_set_width(ui_Screen3_Label32, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Screen3_Label32, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Screen3_Label32, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Screen3_Label32, "BACK TO \nMAIN MENU");

    ui_Screen5_Button3 = lv_btn_create(ui_Screen5);
    lv_obj_set_width(ui_Screen5_Button3, 121);
    lv_obj_set_height(ui_Screen5_Button3, 50);
    lv_obj_set_x(ui_Screen5_Button3, -259);
    lv_obj_set_y(ui_Screen5_Button3, 194);
    lv_obj_set_align(ui_Screen5_Button3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Screen5_Button3, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Screen5_Button3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Screen5_Button3, lv_color_hex(0x151515), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen5_Button3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Screen5_Label1 = lv_label_create(ui_Screen5_Button3);
    lv_obj_set_width(ui_Screen5_Label1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Screen5_Label1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Screen5_Label1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Screen5_Label1, "SAVE DATA");

    ui_Screen1_Panel5 = lv_obj_create(ui_Screen5);
    lv_obj_set_width(ui_Screen1_Panel5, 238);
    lv_obj_set_height(ui_Screen1_Panel5, 172);
    lv_obj_set_x(ui_Screen1_Panel5, 5);
    lv_obj_set_y(ui_Screen1_Panel5, -6);
    lv_obj_set_align(ui_Screen1_Panel5, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Screen1_Panel5, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_Screen1_Panel5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Screen1_Panel5, lv_color_hex(0x151515), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen1_Panel5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Screen1_Label16 = lv_label_create(ui_Screen1_Panel5);
    lv_obj_set_width(ui_Screen1_Label16, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Screen1_Label16, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Screen1_Label16, 4);
    lv_obj_set_y(ui_Screen1_Label16, -57);
    lv_obj_set_align(ui_Screen1_Label16, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Screen1_Label16, "WARNING!");
    lv_obj_set_style_text_color(ui_Screen1_Label16, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Screen1_Label16, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Screen1_Label16, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Screen1_Label17 = lv_label_create(ui_Screen1_Panel5);
    lv_obj_set_width(ui_Screen1_Label17, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Screen1_Label17, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Screen1_Label17, -3);
    lv_obj_set_y(ui_Screen1_Label17, -4);
    lv_obj_set_align(ui_Screen1_Label17, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Screen1_Label17, "error message");
    lv_obj_set_style_text_color(ui_Screen1_Label17, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Screen1_Label17, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Screen1_Button8 = lv_btn_create(ui_Screen1_Panel5);
    lv_obj_set_width(ui_Screen1_Button8, 100);
    lv_obj_set_height(ui_Screen1_Button8, 50);
    lv_obj_set_x(ui_Screen1_Button8, 0);
    lv_obj_set_y(ui_Screen1_Button8, 48);
    lv_obj_set_align(ui_Screen1_Button8, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Screen1_Button8, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Screen1_Button8, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Screen1_Button8, lv_color_hex(0x1F0675), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen1_Button8, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Screen1_Label18 = lv_label_create(ui_Screen1_Button8);
    lv_obj_set_width(ui_Screen1_Label18, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Screen1_Label18, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Screen1_Label18, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Screen1_Label18, "CLOSE");

    lv_obj_add_event_cb(ui_Screen3_Switch2, ui_event_Screen3_Switch2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Screen3_Switch8, ui_event_Screen3_Switch8, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Screen3_Switch9, ui_event_Screen3_Switch9, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Screen3_Switch10, ui_event_Screen3_Switch10, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Screen3_Button1, ui_event_Screen3_Button1, LV_EVENT_ALL, NULL);

}
