// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

void ui_Screen3_screen_init(void)
{
    ui_Screen3 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Screen3, lv_color_hex(0xA91D3A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Screen3_Button13 = lv_btn_create(ui_Screen3);
    lv_obj_set_width(ui_Screen3_Button13, 158);
    lv_obj_set_height(ui_Screen3_Button13, 102);
    lv_obj_set_x(ui_Screen3_Button13, 25);
    lv_obj_set_y(ui_Screen3_Button13, -155);
    lv_obj_set_align(ui_Screen3_Button13, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Screen3_Button13, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Screen3_Button13, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Screen3_Button13, lv_color_hex(0x151515), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen3_Button13, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Screen3_Button13, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Screen3_Label16 = lv_label_create(ui_Screen3_Button13);
    lv_obj_set_width(ui_Screen3_Label16, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Screen3_Label16, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Screen3_Label16, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Screen3_Label16, "RUN MOTOR");
    lv_obj_set_style_text_font(ui_Screen3_Label16, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Screen3_Button2 = lv_btn_create(ui_Screen3);
    lv_obj_set_width(ui_Screen3_Button2, 159);
    lv_obj_set_height(ui_Screen3_Button2, 111);
    lv_obj_set_x(ui_Screen3_Button2, 27);
    lv_obj_set_y(ui_Screen3_Button2, -36);
    lv_obj_set_align(ui_Screen3_Button2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Screen3_Button2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Screen3_Button2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Screen3_Button2, lv_color_hex(0x151515), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen3_Button2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Screen3_Button2, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Screen3_Label2 = lv_label_create(ui_Screen3_Button2);
    lv_obj_set_width(ui_Screen3_Label2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Screen3_Label2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Screen3_Label2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Screen3_Label2, "STOP MOTOR");
    lv_obj_set_style_text_font(ui_Screen3_Label2, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Screen3_Roller1 = lv_roller_create(ui_Screen3);
    lv_roller_set_options(ui_Screen3_Roller1,
                          "10\n11\n12\n13\n14 \n15\n16\n17\n18\n19\n20\n21\n22\n23\n24\n25\n26\n27\n28\n29\n30\n31\n32\n33\n34\n35\n36\n37\n38\n39\n40\n41\n42\n43\n44\n45\n46\n47\n48\n49\n50\n51\n52\n53\n54\n55\n56\n57\n58\n59\n60",
                          LV_ROLLER_MODE_NORMAL);
    lv_obj_set_width(ui_Screen3_Roller1, 145);
    lv_obj_set_height(ui_Screen3_Roller1, 116);
    lv_obj_set_x(ui_Screen3_Roller1, 192);
    lv_obj_set_y(ui_Screen3_Roller1, 85);
    lv_obj_set_align(ui_Screen3_Roller1, LV_ALIGN_CENTER);
    lv_obj_set_style_text_color(ui_Screen3_Roller1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Screen3_Roller1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Screen3_Roller1, lv_color_hex(0x151515), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen3_Roller1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_Screen3_Roller1, lv_color_hex(0x0824B3), LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen3_Roller1, 255, LV_PART_SELECTED | LV_STATE_DEFAULT);

    ui_Screen3_Button3 = lv_btn_create(ui_Screen3);
    lv_obj_set_width(ui_Screen3_Button3, 180);
    lv_obj_set_height(ui_Screen3_Button3, 109);
    lv_obj_set_x(ui_Screen3_Button3, 26);
    lv_obj_set_y(ui_Screen3_Button3, 88);
    lv_obj_set_align(ui_Screen3_Button3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Screen3_Button3, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Screen3_Button3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Screen3_Button3, lv_color_hex(0x151515), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen3_Button3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Screen3_Button3, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Screen3_Label3 = lv_label_create(ui_Screen3_Button3);
    lv_obj_set_width(ui_Screen3_Label3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Screen3_Label3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Screen3_Label3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Screen3_Label3, "CHANGE SPEED");
    lv_obj_set_style_text_font(ui_Screen3_Label3, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Screen3_Button14 = lv_btn_create(ui_Screen3);
    lv_obj_set_width(ui_Screen3_Button14, 115);
    lv_obj_set_height(ui_Screen3_Button14, 50);
    lv_obj_set_x(ui_Screen3_Button14, 331);
    lv_obj_set_y(ui_Screen3_Button14, -209);
    lv_obj_set_align(ui_Screen3_Button14, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Screen3_Button14, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Screen3_Button14, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Screen3_Button14, lv_color_hex(0x151515), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen3_Button14, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Screen3_Button14, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Screen3_Button14, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Screen3_Button14, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Screen3_Label17 = lv_label_create(ui_Screen3_Button14);
    lv_obj_set_width(ui_Screen3_Label17, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Screen3_Label17, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Screen3_Label17, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Screen3_Label17, "BACK TO \nMAIN MENU");

    ui_Screen3_Panel4 = lv_obj_create(ui_Screen3);
    lv_obj_set_width(ui_Screen3_Panel4, 328);
    lv_obj_set_height(ui_Screen3_Panel4, 63);
    lv_obj_set_x(ui_Screen3_Panel4, 114);
    lv_obj_set_y(ui_Screen3_Panel4, 191);
    lv_obj_set_align(ui_Screen3_Panel4, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Screen3_Panel4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Screen3_Panel4, lv_color_hex(0x151515), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen3_Panel4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Screen3_Panel4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Screen3_Panel4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Screen3_Panel4, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Screen3_Label18 = lv_label_create(ui_Screen3_Panel4);
    lv_obj_set_width(ui_Screen3_Label18, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Screen3_Label18, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Screen3_Label18, 25);
    lv_obj_set_y(ui_Screen3_Label18, 0);
    lv_obj_set_align(ui_Screen3_Label18, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Screen3_Label18, "CURRENT SPEED:                                   ");
    lv_obj_set_style_text_color(ui_Screen3_Label18, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Screen3_Label18, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Screen3_Label18, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Screen3_Panel6 = lv_obj_create(ui_Screen3);
    lv_obj_set_width(ui_Screen3_Panel6, 308);
    lv_obj_set_height(ui_Screen3_Panel6, 254);
    lv_obj_set_x(ui_Screen3_Panel6, -225);
    lv_obj_set_y(ui_Screen3_Panel6, 0);
    lv_obj_set_align(ui_Screen3_Panel6, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Screen3_Panel6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Screen3_Panel6, lv_color_hex(0x151515), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen3_Panel6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Screen3_Switch1 = lv_switch_create(ui_Screen3_Panel6);
    lv_obj_set_width(ui_Screen3_Switch1, 235);
    lv_obj_set_height(ui_Screen3_Switch1, 67);
    lv_obj_set_x(ui_Screen3_Switch1, 4);
    lv_obj_set_y(ui_Screen3_Switch1, -46);
    lv_obj_set_align(ui_Screen3_Switch1, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_Screen3_Switch1, lv_color_hex(0x151515), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen3_Switch1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Screen3_Switch1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Screen3_Switch1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Screen3_Switch1, 2, LV_PART_MAIN | LV_STATE_DEFAULT);


    ui_Screen3_Label22 = lv_label_create(ui_Screen3_Switch1);
    lv_obj_set_width(ui_Screen3_Label22, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Screen3_Label22, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Screen3_Label22, 7);
    lv_obj_set_y(ui_Screen3_Label22, 1);
    lv_obj_set_align(ui_Screen3_Label22, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Screen3_Label22, "FORWARD");
    lv_obj_set_style_text_color(ui_Screen3_Label22, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Screen3_Label22, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Screen3_Label23 = lv_label_create(ui_Screen3_Switch1);
    lv_obj_set_width(ui_Screen3_Label23, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Screen3_Label23, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Screen3_Label23, 8);
    lv_obj_set_y(ui_Screen3_Label23, 0);
    lv_obj_set_align(ui_Screen3_Label23, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Screen3_Label23, "BACK");
    lv_obj_add_flag(ui_Screen3_Label23, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_set_style_text_color(ui_Screen3_Label23, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Screen3_Label23, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Screen3_Label24 = lv_label_create(ui_Screen3_Panel6);
    lv_obj_set_width(ui_Screen3_Label24, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Screen3_Label24, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Screen3_Label24, 0);
    lv_obj_set_y(ui_Screen3_Label24, -95);
    lv_obj_set_align(ui_Screen3_Label24, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Screen3_Label24, "CHOOSE DIRECTION");
    lv_obj_set_style_text_color(ui_Screen3_Label24, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Screen3_Label24, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Screen3_Label24, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Screen3_Switch3 = lv_switch_create(ui_Screen3_Panel6);
    lv_obj_set_width(ui_Screen3_Switch3, 235);
    lv_obj_set_height(ui_Screen3_Switch3, 67);
    lv_obj_set_x(ui_Screen3_Switch3, 0);
    lv_obj_set_y(ui_Screen3_Switch3, 76);
    lv_obj_set_align(ui_Screen3_Switch3, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_Screen3_Switch3, lv_color_hex(0x151515), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen3_Switch3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Screen3_Switch3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Screen3_Switch3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Screen3_Switch3, 2, LV_PART_MAIN | LV_STATE_DEFAULT);


    ui_Screen3_Label5 = lv_label_create(ui_Screen3_Switch3);
    lv_obj_set_width(ui_Screen3_Label5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Screen3_Label5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Screen3_Label5, 7);
    lv_obj_set_y(ui_Screen3_Label5, 1);
    lv_obj_set_align(ui_Screen3_Label5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Screen3_Label5, "AUTO");
    lv_obj_set_style_text_color(ui_Screen3_Label5, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Screen3_Label5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Screen3_Label1 = lv_label_create(ui_Screen3_Switch3);
    lv_obj_set_width(ui_Screen3_Label1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Screen3_Label1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Screen3_Label1, 8);
    lv_obj_set_y(ui_Screen3_Label1, 0);
    lv_obj_set_align(ui_Screen3_Label1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Screen3_Label1, "MANUAL");
    lv_obj_add_flag(ui_Screen3_Label1, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_set_style_text_color(ui_Screen3_Label1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Screen3_Label1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Screen3_Label6 = lv_label_create(ui_Screen3_Panel6);
    lv_obj_set_width(ui_Screen3_Label6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Screen3_Label6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Screen3_Label6, 3);
    lv_obj_set_y(ui_Screen3_Label6, 21);
    lv_obj_set_align(ui_Screen3_Label6, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Screen3_Label6, "CHOOSE MODE");
    lv_obj_set_style_text_color(ui_Screen3_Label6, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Screen3_Label6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Screen3_Label6, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Screen3_Button15 = lv_btn_create(ui_Screen3);
    lv_obj_set_width(ui_Screen3_Button15, 311);
    lv_obj_set_height(ui_Screen3_Button15, 80);
    lv_obj_set_x(ui_Screen3_Button15, -226);
    lv_obj_set_y(ui_Screen3_Button15, 184);
    lv_obj_set_align(ui_Screen3_Button15, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Screen3_Button15, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Screen3_Button15, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Screen3_Button15, lv_color_hex(0x151515), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen3_Button15, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Screen3_Button15, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Screen3_Button15, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Screen3_Button15, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Screen3_Label25 = lv_label_create(ui_Screen3_Button15);
    lv_obj_set_width(ui_Screen3_Label25, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Screen3_Label25, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Screen3_Label25, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Screen3_Label25, "GO TO CUSTOM MODE");
    lv_obj_set_style_text_font(ui_Screen3_Label25, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Screen3_Roller3 = lv_roller_create(ui_Screen3);
    lv_roller_set_options(ui_Screen3_Roller3, "PROGRAM 1\nPROGRAM 2\nPROGRAM 3", LV_ROLLER_MODE_NORMAL);
    lv_obj_set_width(ui_Screen3_Roller3, 145);
    lv_obj_set_height(ui_Screen3_Roller3, 130);
    lv_obj_set_x(ui_Screen3_Roller3, 198);
    lv_obj_set_y(ui_Screen3_Roller3, -94);
    lv_obj_set_align(ui_Screen3_Roller3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Screen3_Roller3, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_set_style_text_color(ui_Screen3_Roller3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Screen3_Roller3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Screen3_Roller3, lv_color_hex(0x151515), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen3_Roller3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_Screen3_Roller3, lv_color_hex(0x0824B3), LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen3_Roller3, 255, LV_PART_SELECTED | LV_STATE_DEFAULT);

    ui_Screen3_Label26 = lv_label_create(ui_Screen3);
    lv_obj_set_width(ui_Screen3_Label26, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Screen3_Label26, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Screen3_Label26, 204);
    lv_obj_set_y(ui_Screen3_Label26, -178);
    lv_obj_set_align(ui_Screen3_Label26, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Screen3_Label26, "SET THE PROGRAM");
    lv_obj_add_flag(ui_Screen3_Label26, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_set_style_text_color(ui_Screen3_Label26, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Screen3_Label26, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Screen3_Label26, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Screen3_Label27 = lv_label_create(ui_Screen3);
    lv_obj_set_width(ui_Screen3_Label27, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Screen3_Label27, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Screen3_Label27, 192);
    lv_obj_set_y(ui_Screen3_Label27, 13);
    lv_obj_set_align(ui_Screen3_Label27, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Screen3_Label27, "SET THE SPEED");
    lv_obj_set_style_text_color(ui_Screen3_Label27, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Screen3_Label27, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Screen3_Label27, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Screen3_Dropdown1 = lv_dropdown_create(ui_Screen3);
    lv_dropdown_set_options(ui_Screen3_Dropdown1, "RIGHT\nLEFT");
    lv_obj_set_width(ui_Screen3_Dropdown1, 309);
    lv_obj_set_height(ui_Screen3_Dropdown1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Screen3_Dropdown1, -226);
    lv_obj_set_y(ui_Screen3_Dropdown1, -165);
    lv_obj_set_align(ui_Screen3_Dropdown1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Screen3_Dropdown1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags



    ui_Screen3_Label12 = lv_label_create(ui_Screen3);
    lv_obj_set_width(ui_Screen3_Label12, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Screen3_Label12, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Screen3_Label12, -222);
    lv_obj_set_y(ui_Screen3_Label12, -207);
    lv_obj_set_align(ui_Screen3_Label12, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Screen3_Label12, "CHOOSE THE MOTOR");
    lv_obj_set_style_text_color(ui_Screen3_Label12, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Screen3_Label12, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_Screen3_Button14, ui_event_Screen3_Button14, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Screen3_Switch1, ui_event_Screen3_Switch1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Screen3_Switch3, ui_event_Screen3_Switch3, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Screen3_Button15, ui_event_Screen3_Button15, LV_EVENT_ALL, NULL);

}
