// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

void ui_Screen6_screen_init(void)
{
    ui_Screen6 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Screen6, lv_color_hex(0xE60B0B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_Screen6, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_Screen6, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Screen6_Button4 = lv_btn_create(ui_Screen6);
    lv_obj_set_width(ui_Screen6_Button4, 147);
    lv_obj_set_height(ui_Screen6_Button4, 73);
    lv_obj_set_x(ui_Screen6_Button4, 28);
    lv_obj_set_y(ui_Screen6_Button4, -156);
    lv_obj_set_align(ui_Screen6_Button4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Screen6_Button4, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Screen6_Button4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Screen6_Button4, lv_color_hex(0xB40808), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen6_Button4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_Screen6_Button4, lv_color_hex(0x940400), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_Screen6_Button4, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Screen6_Button4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Screen6_Button4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Screen6_Button4, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Screen3_Label4 = lv_label_create(ui_Screen6_Button4);
    lv_obj_set_width(ui_Screen3_Label4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Screen3_Label4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Screen3_Label4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Screen3_Label4, "RUN MOTOR");

    ui_Screen6_Button5 = lv_btn_create(ui_Screen6);
    lv_obj_set_width(ui_Screen6_Button5, 147);
    lv_obj_set_height(ui_Screen6_Button5, 76);
    lv_obj_set_x(ui_Screen6_Button5, 28);
    lv_obj_set_y(ui_Screen6_Button5, -71);
    lv_obj_set_align(ui_Screen6_Button5, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Screen6_Button5, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Screen6_Button5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Screen6_Button5, lv_color_hex(0x8B0400), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen6_Button5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_Screen6_Button5, lv_color_hex(0x730400), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_Screen6_Button5, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Screen6_Button5, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Screen6_Button5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Screen6_Button5, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Screen3_Label7 = lv_label_create(ui_Screen6_Button5);
    lv_obj_set_width(ui_Screen3_Label7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Screen3_Label7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Screen3_Label7, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Screen3_Label7, "STOP MOTOR");

    ui_Screen6_Roller2 = lv_roller_create(ui_Screen6);
    lv_roller_set_options(ui_Screen6_Roller2,
                          "10\n11\n12\n13\n14 \n15\n16\n17\n18\n19\n20\n21\n22\n23\n24\n25\n26\n27\n28\n29\n30\n31\n32\n33\n34\n35\n36\n37\n38\n39\n40\n41\n42\n43\n44\n45\n46\n47\n48\n49\n50\n51\n52\n53\n54\n55\n56\n57\n58\n59\n60",
                          LV_ROLLER_MODE_NORMAL);
    lv_obj_set_width(ui_Screen6_Roller2, 145);
    lv_obj_set_height(ui_Screen6_Roller2, 108);
    lv_obj_set_x(ui_Screen6_Roller2, 198);
    lv_obj_set_y(ui_Screen6_Roller2, 6);
    lv_obj_set_align(ui_Screen6_Roller2, LV_ALIGN_CENTER);
    lv_obj_set_style_text_color(ui_Screen6_Roller2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Screen6_Roller2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Screen6_Roller2, lv_color_hex(0xB40808), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen6_Roller2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_Screen6_Roller2, lv_color_hex(0x940400), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_Screen6_Roller2, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_Screen6_Roller2, lv_color_hex(0x0824B3), LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen6_Roller2, 255, LV_PART_SELECTED | LV_STATE_DEFAULT);

    ui_Screen6_Button6 = lv_btn_create(ui_Screen6);
    lv_obj_set_width(ui_Screen6_Button6, 147);
    lv_obj_set_height(ui_Screen6_Button6, 76);
    lv_obj_set_x(ui_Screen6_Button6, 29);
    lv_obj_set_y(ui_Screen6_Button6, 21);
    lv_obj_set_align(ui_Screen6_Button6, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Screen6_Button6, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Screen6_Button6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Screen6_Button6, lv_color_hex(0x830400), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen6_Button6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_Screen6_Button6, lv_color_hex(0x6A0400), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_Screen6_Button6, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Screen6_Button6, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Screen6_Button6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Screen6_Button6, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Screen3_Label8 = lv_label_create(ui_Screen6_Button6);
    lv_obj_set_width(ui_Screen3_Label8, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Screen3_Label8, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Screen3_Label8, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Screen3_Label8, "CHANGE SPEED");

    ui_Screen3_Button7 = lv_btn_create(ui_Screen6);
    lv_obj_set_width(ui_Screen3_Button7, 115);
    lv_obj_set_height(ui_Screen3_Button7, 50);
    lv_obj_set_x(ui_Screen3_Button7, 331);
    lv_obj_set_y(ui_Screen3_Button7, -209);
    lv_obj_set_align(ui_Screen3_Button7, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Screen3_Button7, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Screen3_Button7, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Screen3_Button7, lv_color_hex(0xE60808), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen3_Button7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_Screen3_Button7, lv_color_hex(0xC50808), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_Screen3_Button7, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Screen3_Button7, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Screen3_Button7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Screen3_Button7, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Screen3_Label9 = lv_label_create(ui_Screen3_Button7);
    lv_obj_set_width(ui_Screen3_Label9, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Screen3_Label9, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Screen3_Label9, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Screen3_Label9, "BACK TO \nMAIN MENU");

    ui_Screen6_Panel1 = lv_obj_create(ui_Screen6);
    lv_obj_set_width(ui_Screen6_Panel1, 328);
    lv_obj_set_height(ui_Screen6_Panel1, 63);
    lv_obj_set_x(ui_Screen6_Panel1, 123);
    lv_obj_set_y(ui_Screen6_Panel1, 110);
    lv_obj_set_align(ui_Screen6_Panel1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Screen6_Panel1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Screen6_Panel1, lv_color_hex(0x520000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen6_Panel1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_Screen6_Panel1, lv_color_hex(0x310000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_Screen6_Panel1, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Screen6_Panel1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Screen6_Panel1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Screen6_Panel1, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Screen3_Label10 = lv_label_create(ui_Screen6_Panel1);
    lv_obj_set_width(ui_Screen3_Label10, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Screen3_Label10, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Screen3_Label10, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Screen3_Label10, "CURRENT SPEED:                                   ");
    lv_obj_set_style_text_color(ui_Screen3_Label10, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Screen3_Label10, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Screen6_Panel2 = lv_obj_create(ui_Screen6);
    lv_obj_set_width(ui_Screen6_Panel2, 308);
    lv_obj_set_height(ui_Screen6_Panel2, 254);
    lv_obj_set_x(ui_Screen6_Panel2, -225);
    lv_obj_set_y(ui_Screen6_Panel2, -66);
    lv_obj_set_align(ui_Screen6_Panel2, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Screen6_Panel2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Screen6_Panel2, lv_color_hex(0xD50808), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen6_Panel2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_Screen6_Panel2, lv_color_hex(0x5A0400), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_Screen6_Panel2, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Screen6_Switch4 = lv_switch_create(ui_Screen6_Panel2);
    lv_obj_set_width(ui_Screen6_Switch4, 235);
    lv_obj_set_height(ui_Screen6_Switch4, 67);
    lv_obj_set_x(ui_Screen6_Switch4, 4);
    lv_obj_set_y(ui_Screen6_Switch4, -46);
    lv_obj_set_align(ui_Screen6_Switch4, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_Screen6_Switch4, lv_color_hex(0xD50808), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen6_Switch4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_Screen6_Switch4, lv_color_hex(0xB40808), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_Screen6_Switch4, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Screen6_Switch4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Screen6_Switch4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Screen6_Switch4, 2, LV_PART_MAIN | LV_STATE_DEFAULT);


    ui_Screen6_Label11 = lv_label_create(ui_Screen6_Switch4);
    lv_obj_set_width(ui_Screen6_Label11, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Screen6_Label11, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Screen6_Label11, 7);
    lv_obj_set_y(ui_Screen6_Label11, 1);
    lv_obj_set_align(ui_Screen6_Label11, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Screen6_Label11, "FORWARD");
    lv_obj_set_style_text_color(ui_Screen6_Label11, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Screen6_Label11, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Screen6_Label12 = lv_label_create(ui_Screen6_Switch4);
    lv_obj_set_width(ui_Screen6_Label12, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Screen6_Label12, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Screen6_Label12, 8);
    lv_obj_set_y(ui_Screen6_Label12, 0);
    lv_obj_set_align(ui_Screen6_Label12, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Screen6_Label12, "BACK");
    lv_obj_add_flag(ui_Screen6_Label12, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_set_style_text_color(ui_Screen6_Label12, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Screen6_Label12, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Screen3_Label14 = lv_label_create(ui_Screen6_Panel2);
    lv_obj_set_width(ui_Screen3_Label14, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Screen3_Label14, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Screen3_Label14, 0);
    lv_obj_set_y(ui_Screen3_Label14, -95);
    lv_obj_set_align(ui_Screen3_Label14, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Screen3_Label14, "CHOOSE DIRECTION");
    lv_obj_set_style_text_color(ui_Screen3_Label14, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Screen3_Label14, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Screen6_Switch5 = lv_switch_create(ui_Screen6_Panel2);
    lv_obj_set_width(ui_Screen6_Switch5, 235);
    lv_obj_set_height(ui_Screen6_Switch5, 67);
    lv_obj_set_x(ui_Screen6_Switch5, 0);
    lv_obj_set_y(ui_Screen6_Switch5, 76);
    lv_obj_set_align(ui_Screen6_Switch5, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_Screen6_Switch5, lv_color_hex(0x830400), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen6_Switch5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_Screen6_Switch5, lv_color_hex(0x620400), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_Screen6_Switch5, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Screen6_Switch5, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Screen6_Switch5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Screen6_Switch5, 2, LV_PART_MAIN | LV_STATE_DEFAULT);


    ui_Screen6_Label15 = lv_label_create(ui_Screen6_Switch5);
    lv_obj_set_width(ui_Screen6_Label15, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Screen6_Label15, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Screen6_Label15, 7);
    lv_obj_set_y(ui_Screen6_Label15, 1);
    lv_obj_set_align(ui_Screen6_Label15, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Screen6_Label15, "AUTO");
    lv_obj_set_style_text_color(ui_Screen6_Label15, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Screen6_Label15, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Screen6_Label33 = lv_label_create(ui_Screen6_Switch5);
    lv_obj_set_width(ui_Screen6_Label33, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Screen6_Label33, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Screen6_Label33, 8);
    lv_obj_set_y(ui_Screen6_Label33, 0);
    lv_obj_set_align(ui_Screen6_Label33, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Screen6_Label33, "MANUAL");
    lv_obj_add_flag(ui_Screen6_Label33, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_set_style_text_color(ui_Screen6_Label33, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Screen6_Label33, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Screen3_Label34 = lv_label_create(ui_Screen6_Panel2);
    lv_obj_set_width(ui_Screen3_Label34, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Screen3_Label34, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Screen3_Label34, 3);
    lv_obj_set_y(ui_Screen3_Label34, 21);
    lv_obj_set_align(ui_Screen3_Label34, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Screen3_Label34, "CHOOSE MODE");
    lv_obj_set_style_text_color(ui_Screen3_Label34, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Screen3_Label34, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Screen6_Button8 = lv_btn_create(ui_Screen6);
    lv_obj_set_width(ui_Screen6_Button8, 311);
    lv_obj_set_height(ui_Screen6_Button8, 63);
    lv_obj_set_x(ui_Screen6_Button8, -225);
    lv_obj_set_y(ui_Screen6_Button8, 111);
    lv_obj_set_align(ui_Screen6_Button8, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Screen6_Button8, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Screen6_Button8, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Screen6_Button8, lv_color_hex(0x520000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen6_Button8, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_Screen6_Button8, lv_color_hex(0x200000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_Screen6_Button8, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Screen6_Button8, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Screen6_Button8, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Screen6_Button8, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Screen3_Label35 = lv_label_create(ui_Screen6_Button8);
    lv_obj_set_width(ui_Screen3_Label35, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Screen3_Label35, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Screen3_Label35, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Screen3_Label35, "GO TO CUSTOM MODE");

    ui_Screen6_Roller4 = lv_roller_create(ui_Screen6);
    lv_roller_set_options(ui_Screen6_Roller4, "PROGRAM 1\nPROGRAM 2\nPROGRAM 3", LV_ROLLER_MODE_NORMAL);
    lv_obj_set_width(ui_Screen6_Roller4, 145);
    lv_obj_set_height(ui_Screen6_Roller4, 108);
    lv_obj_set_x(ui_Screen6_Roller4, 200);
    lv_obj_set_y(ui_Screen6_Roller4, -127);
    lv_obj_set_align(ui_Screen6_Roller4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Screen6_Roller4, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_set_style_text_color(ui_Screen6_Roller4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Screen6_Roller4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Screen6_Roller4, lv_color_hex(0xB40808), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen6_Roller4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_Screen6_Roller4, lv_color_hex(0x940400), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_Screen6_Roller4, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_Screen6_Roller4, lv_color_hex(0x0824B3), LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen6_Roller4, 255, LV_PART_SELECTED | LV_STATE_DEFAULT);

    ui_Screen6_Label36 = lv_label_create(ui_Screen6);
    lv_obj_set_width(ui_Screen6_Label36, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Screen6_Label36, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Screen6_Label36, 201);
    lv_obj_set_y(ui_Screen6_Label36, -193);
    lv_obj_set_align(ui_Screen6_Label36, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Screen6_Label36, "SET THE PROGRAM");
    lv_obj_add_flag(ui_Screen6_Label36, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_set_style_text_color(ui_Screen6_Label36, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Screen6_Label36, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Screen6_Label37 = lv_label_create(ui_Screen6);
    lv_obj_set_width(ui_Screen6_Label37, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Screen6_Label37, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Screen6_Label37, 189);
    lv_obj_set_y(ui_Screen6_Label37, -58);
    lv_obj_set_align(ui_Screen6_Label37, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Screen6_Label37, "SET THE SPEED");
    lv_obj_set_style_text_color(ui_Screen6_Label37, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Screen6_Label37, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_Screen3_Button7, ui_event_Screen3_Button7, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Screen6_Switch4, ui_event_Screen6_Switch4, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Screen6_Switch5, ui_event_Screen6_Switch5, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Screen6_Button8, ui_event_Screen6_Button8, LV_EVENT_ALL, NULL);

}
