// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Screen1, lv_color_hex(0x38C52E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Screen1_Dropdown1 = lv_dropdown_create(ui_Screen1);
    lv_obj_set_width(ui_Screen1_Dropdown1, 150);
    lv_obj_set_height(ui_Screen1_Dropdown1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Screen1_Dropdown1, -230);
    lv_obj_set_y(ui_Screen1_Dropdown1, -121);
    lv_obj_set_align(ui_Screen1_Dropdown1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Screen1_Dropdown1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags



    ui_Screen1_Button1 = lv_btn_create(ui_Screen1);
    lv_obj_set_width(ui_Screen1_Button1, 100);
    lv_obj_set_height(ui_Screen1_Button1, 50);
    lv_obj_set_x(ui_Screen1_Button1, -151);
    lv_obj_set_y(ui_Screen1_Button1, 82);
    lv_obj_set_align(ui_Screen1_Button1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Screen1_Button1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Screen1_Button1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Screen1_Label2 = lv_label_create(ui_Screen1_Button1);
    lv_obj_set_width(ui_Screen1_Label2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Screen1_Label2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Screen1_Label2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Screen1_Label2, "Connect");

    ui_Screen1_Button2 = lv_btn_create(ui_Screen1);
    lv_obj_set_width(ui_Screen1_Button2, 100);
    lv_obj_set_height(ui_Screen1_Button2, 50);
    lv_obj_set_x(ui_Screen1_Button2, -271);
    lv_obj_set_y(ui_Screen1_Button2, 82);
    lv_obj_set_align(ui_Screen1_Button2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Screen1_Button2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Screen1_Button2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Screen1_Label3 = lv_label_create(ui_Screen1_Button2);
    lv_obj_set_width(ui_Screen1_Label3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Screen1_Label3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Screen1_Label3, 1);
    lv_obj_set_y(ui_Screen1_Label3, 4);
    lv_obj_set_align(ui_Screen1_Label3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Screen1_Label3, "Scan");

    ui_Screen1_Panel2 = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_Screen1_Panel2, 178);
    lv_obj_set_height(ui_Screen1_Panel2, 130);
    lv_obj_set_x(ui_Screen1_Panel2, 99);
    lv_obj_set_y(ui_Screen1_Panel2, -67);
    lv_obj_set_align(ui_Screen1_Panel2, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Screen1_Panel2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Screen1_Label4 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Screen1_Label4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Screen1_Label4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Screen1_Label4, 92);
    lv_obj_set_y(ui_Screen1_Label4, -108);
    lv_obj_set_align(ui_Screen1_Label4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Screen1_Label4, "enter password");

    ui_Screen1_TextArea2 = lv_textarea_create(ui_Screen1);
    lv_obj_set_width(ui_Screen1_TextArea2, 150);
    lv_obj_set_height(ui_Screen1_TextArea2, 70);
    lv_obj_set_x(ui_Screen1_TextArea2, 95);
    lv_obj_set_y(ui_Screen1_TextArea2, -52);
    lv_obj_set_align(ui_Screen1_TextArea2, LV_ALIGN_CENTER);
    lv_textarea_set_placeholder_text(ui_Screen1_TextArea2, "Placeholder...");



    ui_Screen1_Keyboard1 = lv_keyboard_create(ui_Screen1);
    lv_obj_set_width(ui_Screen1_Keyboard1, 796);
    lv_obj_set_height(ui_Screen1_Keyboard1, 244);
    lv_obj_set_x(ui_Screen1_Keyboard1, -1);
    lv_obj_set_y(ui_Screen1_Keyboard1, 109);
    lv_obj_set_align(ui_Screen1_Keyboard1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Screen1_Keyboard1, LV_OBJ_FLAG_HIDDEN);     /// Flags

    ui_Screen1_Button3 = lv_btn_create(ui_Screen1_Keyboard1);
    lv_obj_set_width(ui_Screen1_Button3, 100);
    lv_obj_set_height(ui_Screen1_Button3, 58);
    lv_obj_set_x(ui_Screen1_Button3, 334);
    lv_obj_set_y(ui_Screen1_Button3, 84);
    lv_obj_set_align(ui_Screen1_Button3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Screen1_Button3, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Screen1_Button3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Screen1_Button4 = lv_btn_create(ui_Screen1);
    lv_obj_set_width(ui_Screen1_Button4, 181);
    lv_obj_set_height(ui_Screen1_Button4, 86);
    lv_obj_set_x(ui_Screen1_Button4, 98);
    lv_obj_set_y(ui_Screen1_Button4, 94);
    lv_obj_set_align(ui_Screen1_Button4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Screen1_Button4, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Screen1_Button4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Screen1_Label1 = lv_label_create(ui_Screen1_Button4);
    lv_obj_set_width(ui_Screen1_Label1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Screen1_Label1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Screen1_Label1, 1);
    lv_obj_set_y(ui_Screen1_Label1, 0);
    lv_obj_set_align(ui_Screen1_Label1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Screen1_Label1, "Check for updates");

    ui_Screen1_Label5 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Screen1_Label5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Screen1_Label5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Screen1_Label5, -235);
    lv_obj_set_y(ui_Screen1_Label5, -166);
    lv_obj_set_align(ui_Screen1_Label5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Screen1_Label5, "No network found");

    lv_obj_add_event_cb(ui_Screen1_TextArea2, ui_event_Screen1_TextArea2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Screen1_Button3, ui_event_Screen1_Button3, LV_EVENT_ALL, NULL);

}
